In [1]:
x = 25
x

25

In [11]:
type(x) 

int

In [12]:
y = 3

In [13]:
py_sum = x + y
py_sum

28

In [14]:
type(py_sum)

int

In [15]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [16]:
type(float_sum)

float

In [18]:
import tensorflow as tf

In [19]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype es opcional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [20]:
x_tf.shape

TensorShape([])

In [21]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [22]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [23]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [24]:
tf_sum.numpy()

np.int16(28)

In [25]:
type(tf_sum.numpy())

numpy.int16

In [26]:
tf_float = tf.Variable(25., dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

In [27]:
import numpy as np

In [28]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [29]:
len(x)

3

In [30]:
type(x)

numpy.ndarray

In [31]:
x[0]

np.int64(25)

In [32]:
type(x[0])

numpy.int64

In [33]:
import torch

In [34]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [35]:
x_pt.shape

torch.Size([])