In [1]:

import torch

In [2]:
xs = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7.])

In [3]:
ys = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37])

In [4]:
def regression(my_x, my_m, my_b):
    return my_m*my_x + my_b

In [5]:
m = torch.tensor([0.9]).requires_grad_()

In [6]:
b = torch.tensor([0.1]).requires_grad_()

In [7]:
i = 7
x = xs[i]
y = ys[i]

In [8]:
x

tensor(7.)

In [9]:
y

tensor(-1.3700)

In [10]:
yhat = regression(x, m, b)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

In [11]:
def squared_error(my_yhat, my_y):
    return (my_yhat - my_y)**2

In [12]:
C = squared_error(yhat, y)
C

tensor([60.3729], grad_fn=<PowBackward0>)

In [13]:
C.backward()

In [14]:
m.grad

tensor([108.7800])

In [15]:
b.grad

tensor([15.5400])

In [16]:
2*x*(yhat.item()-y)

tensor(108.7800)

In [17]:
2*(yhat.item()-y)

tensor(15.5400)

In [18]:
gradient = torch.tensor([[b.grad.item(), m.grad.item()]]).T
gradient

tensor([[ 15.5400],
        [108.7800]])