In [8]:
import pandas as pd
import numpy as np

In [9]:
A = np.array([ [2,3,1], [4,1,5] ]) 

In [10]:
B = np.array([ [2,3], [4,1,], [8,7] ]) 

In [11]:
A

array([[2, 3, 1],
       [4, 1, 5]])

In [12]:
B

array([[2, 3],
       [4, 1],
       [8, 7]])

In [13]:
resultado = np.dot(A,B)

In [14]:
resultado

array([[24, 16],
       [52, 48]])

In [15]:
escalar = 2

In [16]:
resultado2 = np.dot(A,escalar)
resultado2

array([[ 4,  6,  2],
       [ 8,  2, 10]])

In [17]:
# transpuesta
A.T

array([[2, 4],
       [3, 1],
       [1, 5]])

In [18]:
# Ejercicios
A = np.array([ [2,2,5], [2,1,6], [1, 6, 7]]) 
B = np.array([ [2,1,1], [1,9,8], [8, 1, 2]]) 
C = np.array([ [2,3], [1,6], [1, 1]]) 

In [20]:
suma = np.add(A, B)
suma

array([[ 4,  3,  6],
       [ 3, 10, 14],
       [ 9,  7,  9]])

In [22]:
producto_escalar = np.dot(15, A)
producto_escalar

array([[ 30,  30,  75],
       [ 30,  15,  90],
       [ 15,  90, 105]])

In [24]:
producto_matrices = np.dot(A, B)
producto_matrices

array([[46, 25, 28],
       [53, 17, 22],
       [64, 62, 63]])

In [25]:
A.T

array([[2, 2, 1],
       [2, 1, 6],
       [5, 6, 7]])

In [26]:
determinante = np.linalg.det(A)
determinante

np.float64(-18.999999999999996)

In [27]:
A

array([[2, 2, 5],
       [2, 1, 6],
       [1, 6, 7]])

In [28]:
trazado = np.trace(A)
trazado

np.int64(10)