In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([ [2,2,5], [2,1,6], [1, 6, 7]]) 
B = np.array([ [2,1,1], [1,9,8], [8, 1, 2]]) 
C = np.array([ [2,3], [1,6], [1, 1]]) 

In [4]:
np.linalg.det(A)

np.float64(-18.999999999999996)

In [6]:
inversa = np.linalg.inv(A)
inversa

array([[ 1.52631579, -0.84210526, -0.36842105],
       [ 0.42105263, -0.47368421,  0.10526316],
       [-0.57894737,  0.52631579,  0.10526316]])

In [7]:
A.dot(inversa)

array([[1.00000000e+00, 0.00000000e+00, 4.16333634e-17],
       [2.22044605e-16, 1.00000000e+00, 2.77555756e-17],
       [3.33066907e-16, 0.00000000e+00, 1.00000000e+00]])

In [8]:
Am = np.array([ [3, 1, 0], [2,2,1], [0,2,1] ]) 

In [9]:
v = np.array([1,2,3]) 

In [10]:
v.shape

(3,)

In [11]:
resultado = Am.dot(v)
resultado

array([5, 9, 7])

In [13]:
v.T

array([1, 2, 3])

In [14]:
v = np.array([[1,2,3]]) 

In [15]:
v

array([[1, 2, 3]])

In [18]:
v.T

array([[1],
       [2],
       [3]])

In [19]:
resultado = Am.dot(v.T)
resultado

array([[5],
       [9],
       [7]])

In [20]:
u1 = np.array([3,0.5,-2, 0]) 

In [21]:
u2 = np.array([1,2,0, -2]) 

In [22]:
resultado1 = np.dot(u1,4)
resultado1

array([12.,  2., -8.,  0.])

In [23]:
resultado2 = np.dot(u2,-2)
resultado2

array([-2, -4,  0,  4])

In [24]:
suma = np.add(resultado1, resultado2)

In [25]:
suma

array([10., -2., -8.,  4.])