In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

In [3]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [4]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [5]:
np.linalg.norm(X)

np.float64(5.477225575051661)

In [6]:
X_pt = torch.tensor([[1, 2], [3, 4.]])

In [7]:
torch.norm(X_pt)

tensor(5.4772)

In [8]:
X_tf = tf.Variable([[1, 2], [3, 4.]])

In [9]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

In [10]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [11]:
b = np.array([1, 2])
b

array([1, 2])

In [12]:
np.dot(A, b)

array([11, 17, 23])

In [13]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [14]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [15]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [16]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [17]:
b_tf = tf.Variable([1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [18]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

In [19]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [20]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [21]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [22]:
B_pt = torch.from_numpy(B)
B_pt

tensor([[1, 9],
        [2, 0]])

In [23]:
B_pt = torch.tensor([[1, 2], [9, 0]]).T
B_pt

tensor([[1, 9],
        [2, 0]])

In [24]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [25]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [26]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>

In [27]:
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [28]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [29]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [31]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [32]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [33]:
torch.matmul(I, x_pt)

tensor([25,  2,  5])

In [34]:
X_ = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
X_

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
v_ = np.array([[-1, 1, -2]]).T
v_

array([[-1],
       [ 1],
       [-2]])

In [36]:
np.dot(X_, v_)

array([[ -3],
       [ -9],
       [-15]])

In [37]:
q_ =  np.array([[-1, 1, -2], [0, 1, 2]]).T
q_

array([[-1,  0],
       [ 1,  1],
       [-2,  2]])

In [38]:
np.dot(X_, q_)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])

In [39]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

producto_escalar = np.dot(vector_a, vector_b)

In [40]:
producto_escalar

np.int64(32)

In [41]:
res = (1*4)+(2*5)+(3*6)
res

32

In [42]:
A = np.array([ [2,2,5], [2,1,6], [1, 6, 7]]) 
B = np.array([ [2,1,1], [1,9,8], [8, 1, 2]]) 
C = np.array([ [2,3], [1,6], [1, 1]]) 

In [45]:
np.linalg.eigvals(A)

array([11.73655148,  0.67210633, -2.40865781])

In [47]:
autovalores, autovectores = np.linalg.eig(A)

In [48]:
autovalores

array([11.73655148,  0.67210633, -2.40865781])

In [49]:
autovectores

array([[-0.47522504, -0.92973408, -0.24676112],
       [-0.49502442, -0.182405  , -0.80497088],
       [-0.72740084,  0.3198796 ,  0.53956542]])

In [51]:
A_nuevo = np.array([ [2,2,1], [2,1,6], [1, 6, 7]]) 

In [52]:
np.linalg.eigvals(A_nuevo)

array([11.10977223,  1.89022777, -3.        ])

In [53]:
autovalores, autovectores = np.linalg.eig(A_nuevo)

In [54]:
autovalores

array([11.10977223,  1.89022777, -3.        ])

In [55]:
autovectores

array([[-0.20653193, -0.94835307,  0.24077171],
       [-0.52925994, -0.09868632, -0.84270097],
       [-0.82293893,  0.30147547,  0.48154341]])

In [57]:
np.dot(autovalores, autovectores)

array([ -0.8261277 , -11.62695267,  -0.3626082 ])

In [58]:
# Matriz original
A = np.array([[3, 2, 2],
              [2, 3, -2]])

# Descomposición SVD
U, S, Vt = np.linalg.svd(A)

# Convertir S (vector de valores singulares) en una matriz diagonal
S_matrix = np.zeros((U.shape[0], Vt.shape[0]))
np.fill_diagonal(S_matrix, S)

# Reconstrucción de la matriz original
A_reconstructed = np.dot(U, np.dot(S_matrix, Vt))

# Comprobación
print("Matriz original:")
print(A)
print("\nMatriz reconstruida:")
print(A_reconstructed)
print("\n¿La matriz original y la reconstruida son iguales?")
print(np.allclose(A, A_reconstructed))

Matriz original:
[[ 3  2  2]
 [ 2  3 -2]]

Matriz reconstruida:
[[ 3.  2.  2.]
 [ 2.  3. -2.]]

¿La matriz original y la reconstruida son iguales?
True


In [59]:
U, S, Vt = np.linalg.svd(A_nuevo)

In [60]:
U

array([[-0.20653193, -0.24077171,  0.94835307],
       [-0.52925994,  0.84270097,  0.09868632],
       [-0.82293893, -0.48154341, -0.30147547]])

In [61]:
S

array([11.10977223,  3.        ,  1.89022777])

In [62]:
Vt

array([[-0.20653193, -0.52925994, -0.82293893],
       [ 0.24077171, -0.84270097,  0.48154341],
       [ 0.94835307,  0.09868632, -0.30147547]])

In [63]:
S_matrix = np.zeros((U.shape[0], Vt.shape[0]))
S_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.fill_diagonal(S_matrix, S)

In [65]:
example = np.fill_diagonal(S_matrix, S)
example

In [66]:
A_reconstructed = np.dot(U, np.dot(S_matrix, Vt))

In [67]:
A_reconstructed

array([[2., 2., 1.],
       [2., 1., 6.],
       [1., 6., 7.]])