In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

In [7]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [8]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [9]:
np.linalg.norm(X)

np.float64(5.477225575051661)

In [11]:
X_pt = torch.tensor([[1, 2], [3, 4.]])

In [12]:
torch.norm(X_pt)

tensor(5.4772)

In [13]:
X_tf = tf.Variable([[1, 2], [3, 4.]])

In [14]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

In [15]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [16]:
b = np.array([1, 2])
b

array([1, 2])

In [17]:
np.dot(A, b)

array([11, 17, 23])

In [18]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [19]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [20]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [21]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [22]:
b_tf = tf.Variable([1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [23]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

In [24]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [25]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [26]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [27]:
B_pt = torch.from_numpy(B)
B_pt

tensor([[1, 9],
        [2, 0]])

In [28]:
B_pt = torch.tensor([[1, 2], [9, 0]]).T
B_pt

tensor([[1, 9],
        [2, 0]])

In [29]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [30]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [31]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>

In [32]:
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [33]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [34]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [38]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [39]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [40]:
torch.matmul(I, x_pt)

tensor([25,  2,  5])

In [49]:
X_ = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
X_

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
v_ = np.array([[-1, 1, -2]]).T
v_

array([[-1],
       [ 1],
       [-2]])

In [56]:
np.dot(X_, v_)

array([[ -3],
       [ -9],
       [-15]])

In [57]:
q_ =  np.array([[-1, 1, -2], [0, 1, 2]]).T
q_

array([[-1,  0],
       [ 1,  1],
       [-2,  2]])

In [58]:
np.dot(X_, q_)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])