In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5]) 
x

array([25,  2,  5])

In [3]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [4]:
np.linalg.norm(x)

np.float64(25.573423705088842)

In [5]:
x

array([25,  2,  5])

In [6]:
np.abs(25) + np.abs(2) + np.abs(5)

np.int64(32)

In [7]:
(25**2 + 2**2 + 5**2)

654

In [8]:
np.dot(x, x)

np.int64(654)

In [9]:
x

array([25,  2,  5])

In [10]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

np.int64(25)

In [11]:
i = np.array([1, 0])
i

array([1, 0])

In [12]:
j = np.array([0, 1])
j

array([0, 1])

In [13]:
np.dot(i, j)

np.int64(0)