In [34]:
import numpy as np
import torch
import tensorflow as tf

In [35]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [36]:
len(x)

3

In [37]:
x.shape

(3,)

In [38]:
type(x)

numpy.ndarray

In [39]:
x[0]

np.int64(25)

In [40]:
x_t = x.T
x_t

array([25,  2,  5])

In [41]:
x_t.shape

(3,)

In [42]:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [43]:
y.shape

(1, 3)

In [44]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [45]:
y_t.shape

(3, 1)

In [46]:
y_t.T

array([[25,  2,  5]])

In [47]:
y_t.T.shape

(1, 3)

In [48]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [49]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [55]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [56]:
x

array([25,  2,  5])